---
title: Introduction to the sparrowtelomeres Package
author: Nathan Brouwer
date: '2020-10-01'
slug: introduction-to-the-sparrowtelomeres-package
categories: []
tags: []
math: no
meta: yes
toc: yes
---


<!--more-->

## Overview

This package contains 3 things

1. A replication of statistical results in Meillere et al (2015) Traffic noise exposure affects telomere length in nestling house sparrows.  Bilogy Letters 11: 20150559.  https://doi.org/10.1098/rsbl.2015.0559
1. Readings and exercises based on Meillere et al. (2015) designed for introductory biology courses.  Some of these use a reduced dataset to simplify analyses.
1. Examples of data visualization techinques using the data from Meillere et al. (2015)

## Key files

TODO: pre-recitation exercise

1. Data preparation: Access data from origianl sources, prepare data for analysis, and save data within the sparrowtelomeres package as .csv and .RData files.
1. Replication: Replication of all statistical results and graphs in the original paper.  All original results replicate, with minor variations due to how p-values are calculated.
1. Abridged & annotated version of Meillere et al (2015): I have re-formatted, abridged, and annotated the original paper to make it more accessible to0 first-year biology undergraduates.  Changes made are summarized below.
1. Pre-recitation exercise: In progress
1. Recitation exercise (with key): An exercise using data from the paper to teach students about data visualization, data interpretation and confidence intervals.
1. Post-recitation exercise: An exercise based on the abridged version of the paper to be completed after the recitation.
1. Beeswarm plot handout: 1-page presentation of the raw data, means and confidence intervals from the paper as a "beeswarm" plot (https://www.r-statistics.com/2011/03/beeswarm-boxplot-and-plotting-it-with-r/)
1. Boxplot handout: 1-page presentation of the data as boxplots.
1. Errorplot handout: 1-page presentation of the means and confidence intervals of the data.
1. 4-plot handout: 1-page presenation of the data in different formats (scatterplot, boxplot, etc).


## Abridged & Annotated Version of Meillere et al (2015)

The following types of chagnes were made to the abridged and annotated version of the paper:

1. Overall the paper was shortened, techincal terms removed or annotated with definitions, and techncial language simplified.
1. The abstract was converted to a structured formated with numbered bullets, which studies have shown increases comprehension.
1. Added keywords
1. Simplified the presentation of the methods 
1. Created a subset of the data which yielded similar results but which could be analyzed using basic statistics instead of mixed models.
1. Generated new statistical results and graphs using the data.



