---
title: Learning Machine Learning for Ecology
author: Nathan Brouwer
date: '2020-12-17'
slug: learning-machine-learning-for-ecology
categories: 
  - machine learning
tags:
  - learnr
  - biology
  - ecology
math: no
meta: yes
toc: yes
draft: yes
excerpt: "An annotated bibliography of ML for ecologists."
---


<!--more-->


Breiman, L., et al. 2001. Statistical modeling: the two cultures (with comments and a rejoinder by the author). Statistical Science 16:199–231.


Morris, C.W., Autret, A., Boddy, L., 2001. Support vector machines for identifying organisms a comparison with strongly partitioned radial basis function networks. Ecological Modelling 146, 57–67.


Drake, J. M., C. Randin, and A. Guisan. 2006. Modelling ecological niches with support vector machines. Journal Applied Ecology 43:424–432.


Classification and regression trees: a powerful yet simple technique for ecological data analysis
G De'ath, KE Fabricius - Ecology, 2000 - Wiley Online Library

Friedman, J.H. & Meulman, J.J. (2003) Multiple additive regression trees with application in
epidemiology. Statistics in Medicine, 22, 1365-1381.

Hastie, T., R. Tibshirani, and J. H. Friedman. 2001. The Elements of Statistical Learning: Data Mining,
Inference, and Prediction. Springer-Verlag, New York.

Bland, L. M., B. E. N. Collen, C. David, L. Orme, and J. O. N. Bielby. 2015. Predicting the conservation status of data-deficient species. Conservation Biology 29:250–259.
DATA?

Newer classification and regression tree techniques: bagging and random forests for ecological prediction.  AM Prasad, LR Iverson, A Liaw - Ecosystems, 2006 - Springer

Hengl, T., M. Nussbaum, M. N. Wright, G. B. M. Heuvelink, and B. Gr€aler. 2018. Random forest as a generic framework for predictive modeling of spatial and spatio-temporal variables.
PeerJ 6:e5518.

Crisci, C., B. Ghattas, and G. Perera. 2012. A review of supervised machine learning algorithms and their applications to ecological data. Ecological Modelling 240:113–122


A working guide to boosted regression trees J Elith, JR Leathwick, T Hastie - Journal of Animal Ecology, 2008 - Wiley Online Library
HAS CODE / DATA


A random forest guided tour.  2016.  Test.




A translucent box: interpretable machine learning in ecology TCD Lucas - Ecological Monographs, 2020 - Wiley Online Library
HAS CODE / DATA


W€aldchen, J., and P. M€ader. 2018. Machine learning for image based species identification. Methods in Ecology and Evolution
9:2216–2225.


Statistically reinforced machine learning for nonlinear patterns and variable interactions
M Ryo, MC Rillig - Ecosphere, 2017 - Wiley Online Library

## Medicine

Mixed effect machine learning: a framework for predicting longitudinal change in hemoglobin
Data open access, but not code.  ADVANCED


Vayena, E., A. Blasimme, and I. G. Cohen. 2018. Machine learning in medicine: addressing ethical challenges. PLoS Medicine 15:e1002689.

