---
title: 'Hello biodata!'
author: Nathan Brouwer
date: '2021-03-01'
slug: ''
categories:
  - biodata
tags:
  - data
  - data science
  - statistics
  - biostatistics
math: no
meta: yes
toc: yes
draft: no
excerpt: "Introducing biodata, a repository for open access datasets for biology and the life sciences."
---


<!--more-->

A constant challenge both as a teacher and learner of data science is finding data sets to use.  As a teacher, I needed datasets my students find interesting for demonstrating methods, to use for assignments and test questions, and to recommend to students for use in research projects or further study.  As a learner, working with different types of data allows you to explore new methods and sharpen your intuitions.  

Sadly, most scientific data outside of genomic sequence data is not available publicly.  Luckily, the last decade or so has seen the birth of a widespread [open science](https://en.wikipedia.org/wiki/Open_science) movement.  Interpretation and adherence to the spirit "open science" varies though, and even the concept of [open data](https://en.wikipedia.org/wiki/Open_data) is inconsistently interpreted, applied and enforced.  

Ideally, an open dataset would be the complete set of raw data used for an entire paper, often called **analysis data**.  In practice, researchers often say they'll make their data available but don't (sometimes even posting bogus references to datasets), don't post all of the data, post the summary data used to make figures but not the raw **analysis data**, use annoying formats such as PDFs, or don't post all of the data to a paper.


## Introducing biodata

In order to meet my needs for open data sets -- and most importantly keep track of things when I've found them -- I've created the [biodata package](https://github.com/brouwern/biodata) in R.  biodata has 4 main goals:

1. Be a general repository for example data sets for biology and the life sciences in general (neuroscience, medical sciences, etc).
1. Be a repository for data sets used in computational replication projects I do with my students.
1. Provide example visualizations and analyses related to the datasets. 
1. Compile practice problems and worked examples for classes involving data analysis.
1. Provide functions useful for generating practice datasets for students.  For example, generating biologically realistics random data, or selecting random subsets of large datasets.

## Installing biodata

biodata lives on [github](https://github.com/brouwern/biodata) and has a [homepage](https://brouwern.github.io/biodata/) where its contents can easily be browsed, including vignettes with worked analyses and help pages for each datasets and introductory examples.

To download biodata you need the devtools package.  You can then install biodata directly from GitHub

```{r, echo = T, eval = F}
# Uncomment this if you need devtools
## install.packages("devtools")
devtools::install_github("brouwern/biodata")
```


## Contributing to biodata

Any dataset related to biology, ecology, evolution, neuroscience, medicine, physiology etc. could be included.  If you have an open access dataset you'd like to contribute to biodata, feel free to contact me at brouwern@gmail.com.  Future blog posts will document my workflow for the package so others can easily contribute. 

