---
title: Hello lobrowR !
author: Nathan Brouwer
date: '2020-12-30'
slug: hello-biodata-blog
categories:
  - R
tags: 
  - R
  - R101
math: no
meta: no
toc: no
---

Welcome to the **lobrowR blog**.  I've been teaching R, statistics for biologists, and computational biology for several years now, accumulating a mound of erratically organized handouts, datasets and exercises.  **lobrowR** is an attempt to compile and make these teaching materials accessible in a single place.  Alongside the blog I am building up a set of example datasets in a package on GitHub called [biodata](https://github.com/brouwern/biodata)

I'm starting off the blog by taking chapters from an "R for biologists" lab manual I've worked on and releasing the lessons.  Most material in the blog is oriented towards those just beginning their journeys with R, data science, and statistics, but I'll include more advanced topics on bioinformatics,computational biology, the analysis of complex datasets.

If you have any comments or questions please leave a message in the threads, or contact me at brouwern@gmail.com.

<!--more-->
