---
title: 'Data Vis 101: Plots'
author: Nathan Brouwer
date: '2021-01-21'
slug: ''
categories: 
  - R
tags: []
math: no
meta: yes
toc: yes
editor_options: 
  chunk_output_type: console
---


<!--more-->

## Types of plots


```{r echo = F}
# This script makes example of different kinds of plots using the telomere data 
# of Meillere et al 2015.

# Prep stuff
## libraries
library(ggpubr)
library(cowplot)
library(dplyr)
library(docxtractr)


file.url <-  "https://royalsocietypublishing.org/action/downloadSupplement?doi=10.1098%2Frsbl.2015.0559&file=rsbl20150559supp1.docx"

### Works with the URL too
file.docx <- docxtractr::read_docx(file.url)
docx.table.list <- docxtractr::docx_extract_all_tbls(docx = file.docx)


## Call each table from list
### nestlings
parus_telos_nest <- docx.table.list[[1]]



```


```{r, echo = F}
# clean up data
parus_telos_nest$cort <- as.numeric(parus_telos_nest$cort)
parus_telos_nest$telomere.length <- as.numeric(parus_telos_nest$telomere.length)

parus_telos_nest$Group <- with(parus_telos_nest,
                       paste(treatment,sex))

parus_telos_nest$Group <- gsub("control","Control",parus_telos_nest$Group)
parus_telos_nest$Group <- gsub("disturbed","Noise exposure",parus_telos_nest$Group)

parus_telos_nest$Group <- gsub(" F","\nFemales",parus_telos_nest$Group)
parus_telos_nest$Group <- gsub(" M","\nMales",parus_telos_nest$Group)
parus_telos_nest$cort.log <- log(parus_telos_nest$cort)
parus_telos_nest$telomere.length.log <- log(parus_telos_nest$telomere.length)


names(parus_telos_nest) <- gsub("treatment",
                        "Treatment",
                        names(parus_telos_nest))

names(parus_telos_nest) <- gsub("sex",
                        "Sex",
                        names(parus_telos_nest))
```




```{r echo = F}
## Re-code data
dat.focal.cols <- parus_telos_nest[,c("Treatment","Sex","telomere.length","cort")]
dat.foc.cols.rnd <- dat.focal.cols
dat.foc.cols.rnd$telomere.length <- dat.foc.cols.rnd$telomere.length %>% round(1)
dat.foc.cols.rnd <- dat.foc.cols.rnd  %>% dplyr::arrange(Treatment,telomere.length)

# dat.foc.cols.rnd %>% 
#   group_by(Treatment) %>% 
#   summarise(sample.size = n(),
#             min.telomere = min(telomere.length),
#             max.telomore = max(telomere.length))
```

```{r echo = F, eval = F}
# expand.grid(telomere.bin  = seq(0.7,1.6,0.1),
#             control = "",
#             disturbed = "")
```



```{r echo = F, eval = F}
# top of the data frame

dat.head <- dat.focal.cols %>%
  mutate_if(is.numeric, round, 2) %>%
  head() 

# knitr::kable(dat.head)

```





```{r echo = F}
# make scatterplot
scatter. <- ggpubr::ggscatter(data = parus_telos_nest,
          y = "telomere.length",
          x = "cort",
          add = "reg.line",
          #color = white,
          cor.coef = T,
          title = "Scatter plot: 2 continous variables",
          xlab = "Predictor: Blood corticosterone\nconcentration",
          ylab = "Response: Telomere length\n")
```


```{r echo = F}
# make bar plot
bar. <- ggpubr::ggbarplot(data = parus_telos_nest,
          y = "telomere.length",
          x = "Treatment",
          fill = "Treatment",
          palette = c("white","black"),
          add = "mean_ci",
          title = "Bar plot: means & error bars",
          xlab= "Predictor: Experimental group\n",
          ylab= "Response: Telomere length\n")
```


```{r echo = F}
#make errror plot
error. <-
  ggpubr::ggerrorplot(data = parus_telos_nest,
          y = "telomere.length",
          x = "Group",
          desc_stat = "mean_ci",
          size =2,
          color = "Treatment"  , 
          title = "Error plot: means & error bars",
          xlab= "Predictor: Experimental group\n",
          ylab= "Response: Telomere length\n") 
```



```{r echo = F, warning = F, message = F}
# make histogram
hist. <- gghistogram(data = parus_telos_nest,
          x = "telomere.length",
          desc_stat = "mean_ci",
          title = "Histogram: Distribution of 1 variable",
          #fill = "sex",
          xlab  = "X-axis: Variable of interest\nTelomere length",
          ylab = "Y-axis: Number of observations\n")
```




```{r echo = F}
# make boxplot
box. <- ggboxplot(data = parus_telos_nest,
          y = "telomere.length",
          x = "Treatment",
          fill = "Treatment",
          title = "Box plot: Distribution of 2 groups",
          xlab= "Predictor: Experimental group",
          ylab= "Response: Telomere length")
```



```{r, echo = T, warning = F, message = F}
# plot all 4 plots in grid
plot_grid(hist.,    box.,
          scatter.,error.)
```


```{r,echo = F, eval = F}
#Blank histogram - for exercise

gghistogram(data = parus_telos_nest,
          x = "telomere.length",
          desc_stat = "mean_ci",
          title = "Histogram",
          #fill = "sex",
          xlab  = "X-axis: Variable of interest\nTelomere length",
          ylab = "Y-axis: Number of observations\n",
          color = "white",
          xlim = c(0.6,1.8)) + 
  geom_vline(xintercept = seq(0.65,1.85,0.1)) +
  geom_hline(yintercept = seq(0,10,1)) +
  scale_x_continuous(breaks =  seq(0.6,1.8,0.1))
```





```{r echo = F, eval = F}
#empty plot
blank. <- ggscatter(data = parus_telos_nest,
          y = "telomere.length",
          x = "cort",
          #add = "reg.line",
          color = "white",
          #cor.coef = T,
          title = "Generic plot layout",
          xlab = "X-axis: Predictor variable\n(aka independent variable)",
          ylab = "Y-axis: Response variable\n(aka dependent variable)")
```
